services:
    mariadb:
        image: mariadb:10.6
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=laravel
        networks:
            - giphy-network

    app:
        build: .
        ports:
            - "8000:80"
        volumes:
            - ./src:/app
        networks:
            - giphy-network
        depends_on:
            - mariadb
        entrypoint:
            - /usr/local/bin/docker-php-entrypoint.sh
volumes:
    dbdata:

networks:
    giphy-network: