services:
    mariadb:
        image: mariadb:10.6
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=laravel

    app:
        build: .
        ports:
            - "80:8000"
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=password
        volumes:
            - ./src:/app
volumes:
  dbdata: